// Data access for users: parameterized queries, rows in / rows out.
// id, role and created_at are generated by the database; role can never be
// chosen at registration time.

import { pool } from '../../database/pool.js';

const USER_COLUMNS = `
  id,
  email,
  password_hash,
  role,
  created_at
`;

export async function findByEmail(email, db = pool) {
  const result = await db.query(
    `SELECT ${USER_COLUMNS} FROM users WHERE email = $1`,
    [email]
  );
  return result.rows[0] ?? null;
}

export async function findById(id, db = pool) {
  const result = await db.query(
    `SELECT ${USER_COLUMNS} FROM users WHERE id = $1`,
    [id]
  );
  return result.rows[0] ?? null;
}

export async function insertUser({ email, passwordHash }, db = pool) {
  const result = await db.query(
    `INSERT INTO users (email, password_hash)
     VALUES ($1, $2)
     RETURNING ${USER_COLUMNS}`,
    [email, passwordHash]
  );
  return result.rows[0];
}